# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-16 15:45
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tkey',
            field=models.CharField(default=core.models.generate_rtk, max_length=32, unique=True),
        ),
    ]
