# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170417_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.Tank')),
            ],
        ),
        migrations.AlterField(
            model_name='stat',
            name='event',
            field=models.IntegerField(choices=[(1, 'Death'), (2, 'Kill')]),
        ),
    ]
